### ISSUE TITLE
2.0.1 crash

### ISSUE THREAD

**Issue by morrissimo** [randombyte-developer/lottery#12]
Looks like a bstats integration issue..?
https://gist.github.com/morrissimo/012c4c9373ce07018c408934d558d44e

Versions:
* forge-1.12.2-14.23.2.2613-universal.jar
* spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
* SpongeBootstrap-0.6.2.jar
* lottery-2.0.1.jar

`lottery-2.0` works like a champ (maxDeposit check bug notwithstanding) with the same other build versions, btw

And sorry if this is an already-known issue (or even a really obscure pebcak)

**Comment by randombyte-developer** [comment]
My mistake when I fixed a bug. I'll fix this today. Thanks for reporting!

**Comment by randombyte-developer** [comment]
Please try again: https://ore.spongepowered.org/RandomByte/Lottery/versions with `v2.0.2`.

**Comment by morrissimo** [comment]
Looks good! Thanks!
