### ISSUE TITLE
spongepowered/api/event/cause/NameCause

### ISSUE THREAD

**Issue by spruill7716** [randombyte-developer/lottery#13]
When using "/lottery buy 1", I get a message saying:

Error occured while executing command:
org/spongepowered/api/event/cause/NameCause

The server console spits out this:
https://www.dropbox.com/s/0yx1gu6v5pq10b7/Lottery.txt?dl=0

**Comment by randombyte-developer** [comment]
What's the name of the lottery plugin jar file? What's the name of the sponge jar you're running?

**Comment by spruill7716** [comment]
The lottery plugin has the default file name:
lottery-2.0.2.jar

The sponge jar is:
spongeforge-1.12.2-2655-7.1.0-BETA-3056.jar

**Comment by randombyte-developer** [comment]
The crash says this 

java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
28.04 15:37:57 [Server] INFO at com.erigitic.config.TEAccount.withdraw(TEAccount.java:282)

So something with erigitic (don't know what that is) causes the actual error. It seems to be some sort of economy plugin, which crashes when lottery tries to withdraw money.

**Comment by randombyte-developer** [comment]
Ah, it's TotalEconomy. Please report the error on their GitHub and post a link to this issue. But first recheck that you're running TotalEconomy for your sponge version. It seems like you're using a wrong version.

**Comment by spruill7716** [comment]
That was it! I was using a version that was built against API 6. Downloaded the new version and lottery is working fine. Thank you!
