### ISSUE TITLE
Lottery get's wiped on restart

### ISSUE THREAD

**Issue by kristi71111** [randombyte-developer/lottery#17]
Whenever my server auto restarts or crashes the pot get's wiped and everyone who has joined the lottery looses their bough tickets. And as far as I know nobody get' drawed in time. Meaning that the draw time is reset on every restart and so are the bough tickets and this causes players to loose money.

If you need more infromation please tell me and I will try and help as best I can.

**Comment by randombyte-developer** [comment]
Upload your server log to something like pastebin and put the link here. It is intended behaviour that the pot is drawn when the server restarts, but it definitely should reward the winner.

**Comment by kristi71111** [comment]
@randombyte-developer Ohh after testing again I noticed that it actually does give the winner the money however perhaps giving a message saying that they won once they login would be nice?

Closing since it actually works as intended.
