### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by unovalegends** [randombyte-developer/lottery#5]
I keep getting a glitch error report from time to time when players do /info 

here are my logs 

https://pastebin.com/AdNtCiRR

**Comment by randombyte-developer** [comment]
I can't find any error, the file is long and I'm searching from mobile. I'll look into it later.

**Comment by unovalegends** [comment]
12.06 14:53:57 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'lottery info' for source EntityPlayerMP['ToxicMangoes'/9486, l='world', x=-1338.62, y=79.74, z=1009.64]: lateinit property nextDraw has not been initialized

**Comment by unovalegends** [comment]
It's every time I do /lottery info some times it works and sometimes it does that
http://imgur.com/a/wJ3Kx

**Comment by randombyte-developer** [comment]
Hm, I thought this was fixed. Are you using the latest release?

**Comment by randombyte-developer** [comment]
#3

It can be temporarily fixed by a force draw after startup.

**Comment by unovalegends** [comment]
Okay
let me see if I have the latest release

**Comment by randombyte-developer** [comment]
Closed due to inactivity.
