### ISSUE TITLE
Request, 7.1.0?

### ISSUE THREAD

**Issue by PixelmonPRO** [randombyte-developer/lottery#9]
Hello! Update to 7 API?)

**Comment by randombyte-developer** [comment]
Once I have time.

**Comment by PixelmonPRO** [comment]
https://github.com/randombyte-developer/lottery/pull/10

**Comment by randombyte-developer** [comment]
https://github.com/randombyte-developer/lottery/releases/tag/v2.0 Can you test the plugin please? Then I will release it on Ore.

**Comment by randombyte-developer** [comment]
Closed due to inactivity
